#!/usr/bin/env tsx
/**
 * Offline level generator for Lockle.
 * Writes a pre-baked levels.ts that can be used for testing or fallback.
 * The live game uses procedural generation in daily.ts instead.
 *
 * Usage:
 *   npm run generate-levels
 *   npm run generate-levels -- --count 365 --seed 42 --min-moves 3 --max-moves 12
 */

import { generateLevel } from "../src/game/generator.ts";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// ---------------------------------------------------------------------------
// Batch generator
// ---------------------------------------------------------------------------
type Level = { layout: string[]; optimalMoves: number };

function generate(
  count: number,
  startSeed: number,
  minMoves: number,
  maxMoves: number,
): Level[] {
  const levels: Level[] = [];
  let seed = startSeed;
  let attempts = 0;
  const maxAttempts = count * 300;

  // Cycle: 40 % single-switch, 40 % two-switch, 20 % three-switch
  const switchCountFor = (i: number): number => {
    const r = i % 10;
    if (r < 4) return 1;
    if (r < 8) return 2;
    return 3;
  };

  while (levels.length < count && attempts < maxAttempts) {
    const numSwitches = switchCountFor(attempts);
    const level = generateLevel(seed, minMoves, maxMoves, numSwitches);
    seed++;
    attempts++;

    if (!level) continue;

    const key = level.layout.join("|");
    if (!levels.some((l) => l.layout.join("|") === key)) {
      levels.push(level);
      process.stdout.write(
        `\r  ${levels.length}/${count} levels found (${attempts} attempts)`,
      );
    }
  }

  process.stdout.write("\n");

  if (levels.length < count) {
    console.warn(
      `\nWarning: only ${levels.length}/${count} levels after ${attempts} attempts`,
    );
  }

  return levels;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------
function getArg(flag: string, fallback: number): number {
  const i = process.argv.indexOf(flag);
  if (i !== -1 && process.argv[i + 1]) return Number(process.argv[i + 1]);
  return fallback;
}

const COUNT = getArg("--count", 100);
const SEED = getArg("--seed", 1);
const MIN_MOVES = getArg("--min-moves", 3);
const MAX_MOVES = getArg("--max-moves", 12);

console.log(
  `Generating ${COUNT} levels (seed=${SEED}, moves=${MIN_MOVES}–${MAX_MOVES})…`,
);

const levels = generate(COUNT, SEED, MIN_MOVES, MAX_MOVES);
console.log(`\nDone. ${levels.length} levels generated.`);

const stats = levels.reduce<Record<number, number>>((acc, l) => {
  acc[l.optimalMoves] = (acc[l.optimalMoves] ?? 0) + 1;
  return acc;
}, {});
console.log("Optimal move distribution:", stats);

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outPath = join(__dirname, "../src/game/levels.ts");

const lines: string[] = [
  `// Auto-generated by tools/generate.ts — do not edit by hand`,
  `// Regenerate with: npm run generate-levels`,
  `// Note: the live game uses procedural generation in daily.ts instead.`,
  ``,
  `export const LEVELS = [`,
];

for (const level of levels) {
  lines.push(
    `  { layout: ${JSON.stringify(level.layout)}, optimalMoves: ${level.optimalMoves} },`,
  );
}

lines.push(`];`);
lines.push(``);

writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Written to ${outPath}`);
